version: '3.3'

services:

  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
#    configs:
#      - source: elastic_config
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: P@ssw0rd
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk-net

  logstash:
    image: logstash:7.16.2
    ports:
      - "5044:5044"
      - "5200:5000"
      - "9600:9600"
    volumes:
      - ${PWD}\\pipeline\\:/usr/share/logstash/pipeline
      - ${PWD}\\log\\:/var/log/test1
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-net

  kibana:
    image: kibana:7.16.2
    ports:
      - "5601:5601"
    networks:
      - elk-net

networks:
  elk-net:
    driver: overlay
    
volumes:
  # metricbeat:
  elasticsearch-data:
